### PR TITLE
Add loan list skeletons

### PR DESCRIPTION
**Pull request by Adamik10**
#### Link to issue
https://reload.atlassian.net/browse/DDFLSBP-432

#### Description
This PR introduces loading skeletons to the loan list page.

#### Screenshot of the result
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/28546954/f1558ffd-7d75-462b-9e11-5cb631136b71

#### Additional comments or questions
-

### CODE REVIEW

**Comment by spaceo** [comment]
If I checkout the branch and run yarn dev I notice following:

The spacing between the buttons in the header is to wide between the buttons:
image
It should be half according to [this change](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/482/commits/b211d1eaf54e7016ab27fc4689ee9fdda0971e06#diff-7aba47028435a592ea6ca168018948257788cfb3346d82562a0b98971c0d2184R31).
So it is probably not the correct/updated version of the design system that is being referred to in package.json
 
There is `.dpl-list-buttons__buttons` elements that are nested inside of `.dpl-list-buttons__buttons`.  That is incorrect and should be fixed both in this repo and in the design system:
image

**Review by spaceo — CHANGES_REQUESTED** [review]
Looks good but I discovered som oddities. Please look at them :)

**Comment by Adamik10** [comment]
Oookay - so in regards to the first comment you had about the icon margins - I changed that change back in [this commit](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/482/commits/5f16f13825dfda4e0a72d1b72cc7335f8e36e70e) so that it matches the design as was previously.

Aaand the second one - I thought that the deal was to bring the structure over into the design system as it was. This screenshot is taken from release/2024-8-0 and it matches perfectly: 
image

@spaceo

**Comment by spaceo** [comment]
> Oookay - so in regards to the first comment you had about the icon margins - I changed that change back in [this commit](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/482/commits/5f16f13825dfda4e0a72d1b72cc7335f8e36e70e) so that it matches the design as was previously.
> 
> Aaand the second one - I thought that the deal was to bring the structure over into the design system as it was. This screenshot is taken from release/2024-8-0 and it matches perfectly: image
> 
> @spaceo

Ok
1. Fair enough. I changed the margin, honestly, by personal preference. I thought there was too much space between the buttons. Let's just leave it be.
2. Sure, the design system should reflect what is in react. But the problem is here that react is wrong. I changed it in my changes, and I think we should fix it while we're at it .because it is wrong.

**Review by spaceo — COMMENTED** [review]
I wrote some answers. One of them needs to be clarified.

**Comment by Adamik10** [comment]
Great point, @spaceo :)) I have adjusted it now.

**Review by spaceo — APPROVED** [review]
LGTM 👍

**Pull request merged**
