### PR TITLE
Itkdev - dashboard clean up

### PR DESCRIPTION
**Pull request by jeppekroghitk**
#### Link to issue

n/a

#### Description

added missing texts
removed 0 from interface
added styling
remove hardcoded text
refactor WarningBar to accommodate two looks
move pager (because valid html)

#### Screenshot of the result

image

image

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Review by spaceo — CHANGES_REQUESTED** [review]
Is in draft mode - does it need a review?

**Comment by sinejespersen** [comment]
> Is in draft mode - does it need a review?

Yes, but not yet. so draft is on purpose.

**Comment by sinejespersen** [comment]
> Looks ok. I am just in doubt of the "my-_" classes. What are they and why could "mb-_" not be used?

it could. But my can also be used, is one of them preferable?

**Review by spaceo — APPROVED** [review]
LGTM

**Pull request merged**
