### PR TITLE
5541: remove aria labels

### PR DESCRIPTION
**Pull request by sinejespersen**
#### Link to issue

https://platform.dandigbib.org/issues/5541

#### Description

Remove aria labels

#### Screenshot of the result

n/a

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Review by jeppekroghitk — APPROVED** [review]

**Comment by spaceo** [comment]
I miss the reason why this is done. Could you please elaborate?
https://media4.giphy.com/media/s239QJIh56sRW/giphy-downsized-medium.gif?cid=c623cb35ldhrkuxuaofl16yt9ps87nzdm6z5o9i28moivkx9&rid=giphy-downsized-medium.gif&ct=g

**Comment by sinejespersen** [comment]
> 
sdf

**Comment by sinejespersen** [comment]
No aria labels on non-interactive elements

**Review by spaceo — APPROVED** [review]
LGTM 👍

**Pull request merged**
